CREATE TABLE IF NOT EXISTS log_dispositiva (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    tipologia VARCHAR(100) NOT NULL,
    esito VARCHAR(100) NOT NULL,
    CONSTRAINT pk_log_dispositiva PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS param_log_dispositiva (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    valore TEXT NOT NULL,
    id_log_dispositiva INTEGER NOT NULL,
    CONSTRAINT pk_param_log_dispositiva PRIMARY KEY (id),
    CONSTRAINT fk_param_log_dispositiva_log_dispositiva FOREIGN KEY (id_log_dispositiva)
        REFERENCES log_dispositiva (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_param_log_dispositiva_id_log_dispositiva
    ON param_log_dispositiva (id_log_dispositiva);
